spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost/payments_spring?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Europe/Kiev
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

app:
  auth:
    admin:
      password: admin
      email: admin@mail.com
  security:
    jwtSecret: SldUU3VwZXJTZWNyZXRLZXkxMjM0NXF3ZXJ0eXVpb3Bhc2RmZ2hqa2w=
    jwtExpirationInMs: 604800000 # One week
    cors:
      maxCacheTime: 3600 # One hour
